# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 589ff121e360288311c6681fe7dffb0aa4a207713791f3a728f7501b0ff2e8f4967ca5bfba1787e01d9bd959ee5cf39b94ff1c95bb672e1d31c34df33f13b0d9

test:
  secret_key_base: a53346a7b3cecc25e7b8096655ecbc43ebce802f15a46b0aa72b430acbd4bad030de2f9be1b631e3bfac8e460b79fbe885fb8b412f87f2e960e7a0759e9c8dfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
