# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 642d49230fc30ff9d03b70fda697743e8e73c9bcfdf71a6d7639ae8bc9437671efa25d103c8ec37f3a3a10bf505abccef5552638e76fce4b3c97cc0c2d2a07f9

test:
  secret_key_base: 1e1c8fa61ff29dc4fed407c2d89ae9dd0d43e05ce84a18e440bceb3ae3391c58c50784e14efc758df39481209104eeec7c4d2c635748e75b5dc4c4e9bafbe353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
