# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bf998b629257a9034c520a5e96c909065154531e9d9b7244ab437e2e2ecdec1369153e5801694ff554a2558790088234ead6d8534c2a4d3fb5137c679306cd1

test:
  secret_key_base: ad4ef232198350db01fbb5933e6aae317aee54a64989961d96534acd868989e22aea19112f9f378f08a7342422952f0b2820788e9421d28c8c7ea1a318fdc179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
