# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c21d1286d4fd5bd583f7ae858f06a7f5d21d830c5d1b6a9cb25b9d40ec8d69c724abc2b8023867127cff3110d9962a589fec30a6ead27bf5fbb48984dd3fe0e

test:
  secret_key_base: a9526a400e523531d2d866e2ffdd67f0ce67f914d2143de37a3925edafee04d3ba31ca1ac5dae5865de67e55b5843cfe06659207a02c3d12b9d1ac07e24621b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
