# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d11a21701cc130525ca7b9fbbca371a150b502ce746c72b080d3a7e2c0d61a6602815854cfb668d8dde4a0a10cc44076b22375c904234c0a0db8c98237478281

test:
  secret_key_base: 57bc1981daf0e12ce2b4758668c17fb9afbddda236aeee78f48975b67ce068ca9d70d1c76a8409bec58aecd014a9051040414a4d5be8e3d42e4827a5a55f4bab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
