# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7783c5bfc9d893a989f08c43b50e8089413c29fe3b00ff703df2fcd6b2160e7b7a7cb35ec94a39e596e85d9b250eaa45cb36d5e573cc4fcb925d169a37c57a2

test:
  secret_key_base: 237d175f2f0782cc3c30c7fd7094ead880d75ff56c69ffd47e744573c433fe3ee8f4151ced7cb9a6eba8aab233f370c5f6b1640281da9a24ee82ab17749b10d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
