# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bec48e3bd351a90c9d89f6035acb53c7f9b32f35ffaf0a8cf7c68488276fee5aa2b72d68344fbebcd019b839a274e71625b9f35e6e5218459d98b07df2c977c

test:
  secret_key_base: 053d32c69522dc014f64d2aa9d9e2afce394cec055ef1fddfb5f5f5bdca54a4dd6a6fe526137365ab3d72aff5ea34c02f3d76e16e8bac6b4758098e23d13c1e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
