# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16f1ba9a8545a594f0b21ee82d50bff7bf722aad3a244d66e1619cdec5a8d4801134f3f20b9b0eb9053082284fe26dccd7ce029e598102d13a84b96873ec719b

test:
  secret_key_base: 46e83a1a66a6b3ae941fdeb8c6df4a9f93773443dcccb1cd920eeb7b1e480898db9f3e38643c8a50681a9b0e3907bfdedaaeae08ab8bb12982ea70512a3b4598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
